### ISSUE TITLE
USER STORY: Create Contact Page

### ISSUE THREAD

**Issue by GeorgeH23** [GeorgeH23/gym-pro-fitness#14]
Epic:  #13 

As a **user**, I want **to be able to access a "Contact Us" page to get in touch with support** so that **I can easily ask questions, and provide feedback**.

**Tasks**
- [x] Create the "Contact Us" Page
- [x] Create the form
- [x] Create a user-friendly and responsive page

**Acceptance Criteria**
- Users can access the "Contact Us" page from the app
- Users can send messages
- The page is responsive and user-friendly
