### ISSUE TITLE
EPIC: Routines and Workouts

### ISSUE THREAD

**Issue by GeorgeH23** [GeorgeH23/gym-pro-fitness#18]
**Description:** Enhance the gym member experience with a feature allowing users to create personalized workout routines.

**Additional Information:**
- Users will have the ability to create personalized workout routines.
- The system will prioritize user-friendly interfaces

**Linked User Stories:**
- [x] #19 As a gym member, I can create a personalized workout routine
- [x] #22  As a gym member, I can save. edit, delete routines.
- [x] #20 As a gym member, I can explore predefined workouts
