### ISSUE TITLE
USER STORY: View/Edit Account Information

### ISSUE THREAD

**Issue by GeorgeH23** [GeorgeH23/gym-pro-fitness#7]
Epic: #6 

As a **user**, I want **to be able to view and edit my account information** so that **I can keep my account up to date**.

**Tasks**
- [x] Create/Design the User Profile Page
- [x] Get the user account information from the database
- [x] Enable user to edit their account information.
- [x] Implement validation checks
- [x] Update the database with new information of the user

**Acceptance Criteria**
- Users should be able to access their user profile page from navigation menu.
- The user's account information should be displayed on the profile page.
- Editable fields should provide user-friendly input forms for making changes.
- The user's updated information should be stored in the app's database.
